name: '[Development] BFF CI/CD Pipeline'

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  AWS_ACCOUNT_ID: 630391673963
  ENVIRONMENT: development
  ECR_HOST: 630391673963.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY_NAME: talent-bff-service
  ECR_REPOSITORY: 630391673963.dkr.ecr.ap-southeast-1.amazonaws.com/talent-bff-service

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::630391673963:role/github-actions-role-development
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
              ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Get short SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA}}  -f Dockerfile.bff .
          docker push ${{ env.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA}}
